### PR TITLE
[WIP] Replace prepend implementation and allow better subclass functionality

### PR DESCRIPTION
**Pull request by aprescott**
* [ ] Wait for a Sidekiq release later than 3.3.0.

This addresses #3.

As of mperham/sidekiq#1943, a couple of things need to change in the implementation and in the tests.

The first is that `prepend` is no longer necessary, because `execute_job` is now a level of indirection that sits in front of `perform`. The `execute_job` method is intended to provide a wrapper around `perform` so that modifications can be made. This gem provides such a modification, so implementation is somewhat cleaner.

The second change is to the tests. Previously, we were calling `.perform` directly in order to verify that the `perform` call was modifying code. Since the new code is now testing that `execute_job` is modifying the arguments passed to `perform`, this test is unnecessary.

This commit also removes the requirement that every job class `include Sidekiq::Symbols`, even if a parent class already did it. Say you have this structure:

```ruby
class ApplicationJob
  include Sidekiq::Worker
  include Sidekiq::Symbols

  # ...
end

class FooJob < ApplicationJob
  def perform(x: 1)
    # ...
  end
end
```

Enqueueing a job for `FooJob` would _not_ allow symbol usage in the existing, previous implementation, because `ApplicationJob` is the class that `Sidekiq::Symbols` was prepended in front of.

```
  ApplicationJob
        |
  Sidekiq::Symbols
        |
      FooJob
```

Soo `FooJob` (and every other subclass of `ApplicationJob`) had to explicitly duplicate the `include Sidekiq::Symbols` line unless it called `super` or something similar.

With the new implementation, there is no `prepend`ed module, and instead `ApplicationJob` defines its own `execute_job`, which every subclass will also use.

This helps address #2.

### CODE REVIEW

**Comment by PikachuEXE** [comment]
@aprescott `sidekiq` latest version is `3.3.3`, you can update this PR :)
I will test it once updated

**Comment by aprescott** [comment]
@PikachuEXE thanks! I actually need to change back to the `prepend` implementation for various reasons, including https://github.com/mperham/sidekiq/pull/2097#issuecomment-68078612. I'll try to get this stuff sorted out though so that subclassing works.

**Comment by mhenrixon** [comment]
Any updates on this?

**Comment by aprescott** [comment]
I've replaced this with #7.

**Comment by aprescott** [comment]
@mhenrixon feel free to take a look at the new PR! Thoughts welcome. :)

**Pull request closed without merging**
